---
Name: delectus-search-config
After:
  - 'delectus/*'
---
Injector:
  DelectusSearchService:
    class: DelectusSearchService
DelectusSearchModule:
  version: 'v1'
DelectusTransport:
  endpoints:
    search: 'https://api.delectus.io/'
