---
Name: delectus-search-config
After:
  - 'delectus/*'
---
ContentController:
  extensions:
    - DelectusSearchControllerExtension
DelectusSearchService:
  module_name: 'delectus-search'
  version: 'v1'
  endpoints:
    search: 'https://api.delectus.io/'
#  client_token: ''     these should be set in your website config yaml or can be set in CMS settings tab
#  client_salt: ''
#  site_identifier: ''
