---
Name: delectus-search-config
After:
  - 'delectus/*'
---
Injector:
  DelectusSearchModule:
    class: DelectusSearchModule
  DelectusSearchService:
    class: DelectusSearchService
    properties:
      module: %$DelectusSearchModule
DelectusSearchModule:
  version: 'v1'
DelectusTransport:
  endpoints:
    search: 'https://api.delectus.io/'
