---
Name: delectus-search-config
After:
  - 'delectus/*'
---
DelectusSearchModule:
  version: 'v1'
#  client_token: ''     these should be set in your website config yaml or can be set in CMS settings tab
#  client_salt: ''
#  site_identifier: ''
DelectusSearchService:
  module_name: 'delectus-search'
DelectusTransport:
  endpoints:
    search: 'https://api.delectus.io/'
